// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package src

import (
	"github.com/nazudis/disbursement/engine/rest/controller"
	"github.com/nazudis/disbursement/engine/rest/transformer"
	"github.com/nazudis/disbursement/src/database"
	"github.com/nazudis/disbursement/src/dependencies/mockapi"
	"github.com/nazudis/disbursement/src/repository"
	"github.com/nazudis/disbursement/src/service"
)

// Injectors from injector.go:

func InitializeAuthController() (controller.AuthController, error) {
	db := database.GetDB()
	clientRepository := repository.NewClientRepository(db)
	authSessionRepository := repository.NewAuthSessionRepository(db)
	authService := service.NewAuthService(clientRepository, authSessionRepository)
	authTransformer := transformer.NewAuthTransformer()
	authController := controller.NewAuthController(authService, authTransformer)
	return authController, nil
}

func InitializeTransactionController() (controller.TransactionController, error) {
	mockApi := mockapi.NewMockApi()
	db := database.GetDB()
	transactionRepository := repository.NewTransactionRepository(db)
	walletRepository := repository.NewWalletRepository(db)
	transactionService := service.NewTransactionService(mockApi, transactionRepository, walletRepository)
	transactionTransformer := transformer.NewTransactionTransformer()
	transactionController := controller.NewTransactionController(transactionService, transactionTransformer)
	return transactionController, nil
}
